spring:
  application:
    name: Assets-Management-App
  datasource:
    url: jdbc:postgresql://103.133.215.182:5432/gloitel_db_ams
    username: gloitel
    password: gloitel123
    driver-class-name: org.postgresql.Driver
  # datasource:
    # url: jdbc:postgresql://localhost:5432/assetdb
    # username: postgres
    # password: 1234
    # driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    # show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:vinayvastrakar13@gmail.com}
    password: ${MAIL_PASSWORD:ywaqzzglegkqnayw}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    contentnegotiation:
      favor-parameter: true

jwt:
  secret: asdfgvhgvgkhafjhcaaaaaaaaaaaabbbbbbbbdjhhheeeeeeeeeeejjjjjjjjjjjkkkkkkkkkkkkkkkkkssssssssssskaaaaaaaaaaaaaaaaaaaaaaadddddddasdhbauhegfahdcbsjdvaghsdvaskjhsvgvrysecretkeysdscscscscscscscscscscscscscscscsdccccccccccccccccccccccccccccccccccccccccrfbfdgndfgsdgnnnnnnfsngsgnsgnsdljkfvbahvbjkdfbjasdhfajkldvbjhfbhsdbfvdfhlvafbvahldbfgvfhhadfbadrhbjkvndfkjnvjatgiah
  expiration: 43200000 #12Hrs
  refresh-expiration: 172800000 #48Hrs

# Google OAuth Configuration
google:
  client:
    id: ${GOOGLE_CLIENT_ID:415874474219-kjid0pm06qmuvnven29tgio20mb1hoah.apps.googleusercontent.com}