# Production Profile Configuration
spring:
  # Database configuration (must be set via environment variables)
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  
  # Email configuration
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Brevo API Configuration for Production
brevo:
  enabled: ${BREVO_ENABLED:true}
  api:
    key: ${BREVO_API_KEY}
  sender:
    email: ${BREVO_SENDER_EMAIL}
    name: ${BREVO_SENDER_NAME:Asset Management App}

# Production-specific settings
logging:
  level:
    com.example.Assets.Management.App: ${LOGGING_LEVEL_COM_EXAMPLE_ASSETS_MANAGEMENT_APP:INFO}
    org.springframework.mail: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_MAIL:WARN}
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

# JWT Configuration for production
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:43200000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:172800000}

# Google OAuth Configuration
google:
  client:
    id: ${GOOGLE_CLIENT_ID}

# Server configuration for production
server:
  port: ${SERVER_PORT:8080}

# CORS Configuration for production
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

# Security settings for production
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized 